[build]
  publish = "."

[[redirects]]
  from = "/video"
  to = "/video.html"
  status = 200

[[redirects]]
  from = "/presentazione"
  to = "/presentazione.html"
  status = 200

[[redirects]]
  from = "/giudici"
  to = "/giudici.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/giudici.html"
  status = 200
